apiVersion: v2
appVersion: "3.36"
description: Mikrotik Winbox in browser 
name: winbox
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
- winbox
home: https://mikrotik.com/download
icon: https://winbox.org/icon
sources:
- https://github.com/obeone/winbox-docker
maintainers:
- name: winbox
  email: winbox@winbox.com
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.3.0
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
