version: '3.4'
services:
    shm_size: 512m
    image: deepsurvey/winbox-docker:latest
    restart: always
    ports:
    - 6901:6901
    environment:
    - VNC_PW=password
    volumes:
    - winbox_wine:/home/kasm-user/.wine
