name: Build and publish
on:
  schedule:
    - cron: "23 2 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: winbox
  IMAGES: |
    docker.io/obebete/winbox
    ghcr.io/obeone/winbox

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Winbox version
        run: echo "version=$(./winbox_version.sh)" >> GITHUB_OUTPUT

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ env.IMAGES }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}},value=${{ steps.version.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.version.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.version.outputs.version }}
            type=semver,pattern=v{{version}},value=${{ steps.version.outputs.version }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ steps.version.outputs.version }}
            type=semver,pattern=v{{major}},value=${{ steps.version.outputs.version }}

      - name: Publish image
        id: push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          pull: true
          cache-to: type=gha,mode=max
          cache-from: type=gha,mode=max

      - name: Sign the images with GitHub OIDC Token
        run: |
          set -e
          for image in "${TAGS}"; do
            yes | cosign sign ${image}@${DIGEST}
          done
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.push.outputs.digest }}
          COSIGN_EXPERIMENTAL: true
        if: github.event_name != 'pull_request'
